---
name: cmpsc-300-spring-2021-lab3
break: true
indent: 4
---

# --> check the technical writing
writing/report.md:
    ConfirmFileExists
    CountFileWords --count 30
    CountMarkdownTags --tag "heading" --count 3 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact



# --> check the number of commits beyond a threshold
CountCommits --count 3
